"""Add technology system models

Revision ID: 765d8d414750
Revises: e003c637b833
Create Date: 2026-01-03 18:34:06.465390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765d8d414750'
down_revision = 'e003c637b833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('range_level', sa.Integer(), nullable=False),
    sa.Column('speed_level', sa.Integer(), nullable=False),
    sa.Column('weapons_level', sa.Integer(), nullable=False),
    sa.Column('shields_level', sa.Integer(), nullable=False),
    sa.Column('mini_level', sa.Integer(), nullable=False),
    sa.Column('radical_level', sa.Integer(), nullable=False),
    sa.Column('range_progress', sa.Float(), nullable=False),
    sa.Column('speed_progress', sa.Float(), nullable=False),
    sa.Column('weapons_progress', sa.Float(), nullable=False),
    sa.Column('shields_progress', sa.Float(), nullable=False),
    sa.Column('mini_progress', sa.Float(), nullable=False),
    sa.Column('radical_progress', sa.Float(), nullable=False),
    sa.Column('range_budget', sa.Integer(), nullable=False),
    sa.Column('speed_budget', sa.Integer(), nullable=False),
    sa.Column('weapons_budget', sa.Integer(), nullable=False),
    sa.Column('shields_budget', sa.Integer(), nullable=False),
    sa.Column('mini_budget', sa.Integer(), nullable=False),
    sa.Column('radical_budget', sa.Integer(), nullable=False),
    sa.Column('decoy_unlocked', sa.Boolean(), nullable=False),
    sa.Column('biological_unlocked', sa.Boolean(), nullable=False),
    sa.Column('temp_range_bonus', sa.Integer(), nullable=False),
    sa.Column('temp_speed_bonus', sa.Integer(), nullable=False),
    sa.Column('temp_weapons_bonus', sa.Integer(), nullable=False),
    sa.Column('temp_shields_bonus', sa.Integer(), nullable=False),
    sa.Column('temp_bonus_expires_turn', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['game_players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_table('radical_breakthroughs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('eliminated_option', sa.String(length=50), nullable=True),
    sa.Column('unlocked_option', sa.String(length=50), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_turn', sa.Integer(), nullable=False),
    sa.Column('resolved_turn', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['game_players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radical_breakthroughs')
    op.drop_table('player_technologies')
    # ### end Alembic commands ###
