"""Add Fleet, Ship, ShipDesign models

Revision ID: bb7d803a9b19
Revises: 3c829af9a4d8
Create Date: 2025-12-30 23:59:18.760260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7d803a9b19'
down_revision = '3c829af9a4d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ship_designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('ship_type', sa.String(length=20), nullable=False),
    sa.Column('range_level', sa.Integer(), nullable=False),
    sa.Column('speed_level', sa.Integer(), nullable=False),
    sa.Column('weapons_level', sa.Integer(), nullable=False),
    sa.Column('shields_level', sa.Integer(), nullable=False),
    sa.Column('mini_level', sa.Integer(), nullable=False),
    sa.Column('prototype_cost_money', sa.Integer(), nullable=False),
    sa.Column('prototype_cost_metal', sa.Integer(), nullable=False),
    sa.Column('production_cost_money', sa.Integer(), nullable=False),
    sa.Column('production_cost_metal', sa.Integer(), nullable=False),
    sa.Column('is_prototype_built', sa.Boolean(), nullable=False),
    sa.Column('ships_built', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['game_players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fleets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('current_star_id', sa.Integer(), nullable=True),
    sa.Column('orbiting_planet_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('destination_star_id', sa.Integer(), nullable=True),
    sa.Column('departure_turn', sa.Integer(), nullable=True),
    sa.Column('arrival_turn', sa.Integer(), nullable=True),
    sa.Column('travel_path', sa.JSON(), nullable=True),
    sa.Column('fuel_remaining', sa.Float(), nullable=False),
    sa.Column('max_fuel', sa.Float(), nullable=False),
    sa.Column('combat_behavior', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_star_id'], ['stars.id'], ),
    sa.ForeignKeyConstraint(['destination_star_id'], ['stars.id'], ),
    sa.ForeignKeyConstraint(['orbiting_planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['game_players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.Column('fleet_id', sa.Integer(), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.Column('is_destroyed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('destroyed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['design_id'], ['ship_designs.id'], ),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ships')
    op.drop_table('fleets')
    op.drop_table('ship_designs')
    # ### end Alembic commands ###
