"""Add ships_budget to Planet and ProductionQueue table

Revision ID: c1669dafe4ca
Revises: f74e57cc264d
Create Date: 2025-12-31 20:34:08.455997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1669dafe4ca'
down_revision = 'f74e57cc264d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.Column('fleet_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('production_invested', sa.Float(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['design_id'], ['ship_designs.id'], ),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleets.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ships_budget', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ship_production_points', sa.Float(), nullable=True))
        batch_op.alter_column('galaxy_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('x',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('y',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('y',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('x',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('galaxy_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('ship_production_points')
        batch_op.drop_column('ships_budget')

    op.drop_table('production_queue')
    # ### end Alembic commands ###
