"""Add texture fields to planets

Revision ID: e003c637b833
Revises: c1669dafe4ca
Create Date: 2026-01-02 13:27:51.417164

"""
from alembic import op
import sqlalchemy as sa
import random


# revision identifiers, used by Alembic.
revision = "e003c637b833"
down_revision = "c1669dafe4ca"
branch_labels = None
depends_on = None


def determine_texture_type(temperature, gravity, metal_reserves):
    """Determine texture type based on planet characteristics."""
    temp_factor = max(0, 1 - abs(temperature - 22) / 100)
    gravity_factor = max(0, 1 - abs(gravity - 1.0) / 2)
    habitability = temp_factor * gravity_factor

    if gravity < 0.3 or gravity > 2.5:
        return "gas"
    if metal_reserves < 100 and habitability < 0.2:
        return "barren"
    if temperature > 80:
        return "volcanic"
    if temperature < -50:
        return "ice"
    if temperature > 30:
        return "desert"
    if habitability > 0.3:
        return "habitable"
    return "barren"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("planets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("texture_type", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("texture_index", sa.Integer(), nullable=True))

    # Backfill existing planets with texture data
    connection = op.get_bind()
    planets = connection.execute(
        sa.text("SELECT id, temperature, gravity, metal_reserves FROM planets WHERE texture_type IS NULL")
    ).fetchall()

    for planet in planets:
        planet_id, temperature, gravity, metal_reserves = planet
        texture_type = determine_texture_type(temperature, gravity, metal_reserves)
        texture_index = random.randint(1, 100)
        connection.execute(
            sa.text("UPDATE planets SET texture_type = :type, texture_index = :idx WHERE id = :id"),
            {"type": texture_type, "idx": texture_index, "id": planet_id}
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("planets", schema=None) as batch_op:
        batch_op.drop_column("texture_index")
        batch_op.drop_column("texture_type")

    # ### end Alembic commands ###
